name: Testing

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ['continuumio/miniconda3:latest', 'condaforge/miniforge3:latest']
        platform: [arm64, ppc64le]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Run Tests
        run: docker run
          --rm
          --volume ${PWD}:/opt/conda-src
          --workdir /opt/conda-src
          --platform linux/${{ matrix.platform }}
          ${{ matrix.image }}
          sh -c
          "conda info --verbose
          && conda list --show-channel-urls"
