name: Testing

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: debian:stable-slim

    steps:
      - run: echo "hello world"
        shell: bash