name: Testing

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: debian:stable-slim
      options: --platform linux/arm64

    steps:
      - run: echo "hello world"
        shell: bash

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          run-post: false  # skip post cleanup

      - name: Show Info
        run: |
          conda info --verbose
          conda list --show-channel-urls